doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            json_array: Wallabag\CoreBundle\Doctrine\JsonArrayType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

when@prod:
    #doctrine:
    #    orm:
    #        metadata_cache_driver: apc
    #        result_cache_driver: apc
    #        query_cache_driver: apc

when@dev:
    # If you want to use cache for queries used in WallabagExtension
    # Uncomment the following lines
    #doctrine:
    #    orm:
    #        metadata_cache_driver: apcu
    #        result_cache_driver: apcu
    #        query_cache_driver: apcu

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test' # for MySQL and PostgreSQL

        orm:
            metadata_cache_driver:
                type: service
                id: filesystem_cache
            query_cache_driver:
                type: service
                id: filesystem_cache
