fos_oauth_server:
    db_driver: orm
    client_class: Wallabag\ApiBundle\Entity\Client
    access_token_class: Wallabag\ApiBundle\Entity\AccessToken
    refresh_token_class: Wallabag\ApiBundle\Entity\RefreshToken
    auth_code_class: Wallabag\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email
        options:
            refresh_token_lifetime: "%fos_oauth_server_refresh_token_lifetime%"
            access_token_lifetime: "%fos_oauth_server_access_token_lifetime%"
