framework:
    router:
        resource: "%kernel.project_dir%/config/routes.yaml"
        strict_requirements: ~

when@dev:
    framework:
        router:
            resource: "%kernel.project_dir%/config/routes/dev/routes.yaml"
            strict_requirements: true
