framework:
    router:
        resource: "%kernel.project_dir%/app/config/routing.yaml"
        strict_requirements: ~

when@dev:
    framework:
        router:
            resource: "%kernel.project_dir%/app/config/routing_dev.yaml"
            strict_requirements: true
