#!/usr/bin/env php
<?php
set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/src/app.php';

$console = $app['console'];

$console->add(new Poche\Command\UnitTestsCommand());

$console->run();
