<?php

namespace Wallabag\CoreBundle\Repository;

/**
 * SiteCredentialRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteCredentialRepository extends \Doctrine\ORM\EntityRepository
{
}
