imports:
    - { resource: config.yml }

parameters:
    env(WALLABAG_SESSION_COOKIE_NAME): PHPSESSID
    env(WALLABAG_REMEMBER_ME_COOKIE_NAME): REMEMBERME
    env(WALLABAG_TRUSTED_DEVICE_COOKIE_NAME): wllbg_trusted_computer

framework:
    session:
        name: "%env(WALLABAG_SESSION_COOKIE_NAME)%"
    router:
        resource: "%kernel.project_dir%/app/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false

    mailer:
        # see https://mailcatcher.me/
        dsn: smtp://127.0.0.1:1025

security:
    firewalls:
        main:
            remember_me:
                name: "%env(WALLABAG_REMEMBER_ME_COOKIE_NAME)%"

scheb_two_factor:
    trusted_device:
        cookie_name: "%env(WALLABAG_TRUSTED_DEVICE_COOKIE_NAME)%"

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        console:
            type: console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ['!event', '!doctrine']
        console_very_verbose:
            type: console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: [doctrine]

# If you want to use cache for queries used in WallabagExtension
# Uncomment the following lines
#doctrine:
#    orm:
#        metadata_cache_driver: apcu
#        result_cache_driver: apcu
#        query_cache_driver: apcu
