imports:
    - { resource: parameters.yml }
    - { resource: security.yaml }
    - { resource: services.yaml }
    - { resource: ../../config/packages/doctrine.yaml }
    - { resource: ../../config/packages/doctrine_migrations.yaml }
    - { resource: ../../config/packages/fos_oauth_server.yaml }
    - { resource: ../../config/packages/fos_rest.yaml }
    - { resource: ../../config/packages/fos_user.yaml }
    - { resource: ../../config/packages/framework.yaml }
    - { resource: ../../config/packages/kphoen_rulerz.yaml }
    - { resource: ../../config/packages/mailer.yaml }
    - { resource: ../../config/packages/monolog.yaml }
    - { resource: ../../config/packages/nelmio_api_doc.yaml }
    - { resource: ../../config/packages/nelmio_cors.yaml }
    - { resource: ../../config/packages/routing.yaml }
    - { resource: ../../config/packages/scheb_two_factor.yaml }
    - { resource: ../../config/packages/sentry.yaml }
    - { resource: ../../config/packages/stof_doctrine_extensions.yaml }
    - { resource: ../../config/packages/translation.yaml }
    - { resource: ../../config/packages/twig.yaml }
    - { resource: ../../config/packages/validator.yaml }
    - { resource: ../../config/packages/wallabag.yaml }
    - { resource: ../../config/packages/web_profiler.yaml }

parameters:
    # Allows to use the live reload feature for changes in assets
    use_webpack_dev_server: false
    craue_config.cache_adapter.class: Craue\ConfigBundle\CacheAdapter\SymfonyCacheComponentAdapter
    env(DATABASE_URL): '%database_scheme%://%database_user%:%database_password%@%database_host%:%database_port%/%database_name%?unix_socket=%database_socket%&charset=%database_charset%'

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     "%rabbitmq_port%"
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost:    /
            lazy:     true
    producers:
        import_pocket:
            connection: default
            exchange_options:
                name: 'wallabag.import.pocket'
                type: topic
        import_readability:
            connection: default
            exchange_options:
                name: 'wallabag.import.readability'
                type: topic
        import_pinboard:
            connection: default
            exchange_options:
                name: 'wallabag.import.pinboard'
                type: topic
        import_delicious:
            connection: default
            exchange_options:
                name: 'wallabag.import.delicious'
                type: topic
        import_instapaper:
            connection: default
            exchange_options:
                name: 'wallabag.import.instapaper'
                type: topic
        import_wallabag_v1:
            connection: default
            exchange_options:
                name: 'wallabag.import.wallabag_v1'
                type: topic
        import_wallabag_v2:
            connection: default
            exchange_options:
                name: 'wallabag.import.wallabag_v2'
                type: topic
        import_elcurator:
            connection: default
            exchange_options:
                name: 'wallabag.import.elcurator'
                type: topic
        import_omnivore:
            connection: default
            exchange_options:
                name: 'wallabag.import.omnivore'
                type: topic
        import_firefox:
            connection: default
            exchange_options:
                name: 'wallabag.import.firefox'
                type: topic
        import_chrome:
            connection: default
            exchange_options:
                name: 'wallabag.import.chrome'
                type: topic
        import_shaarli:
            connection: default
            exchange_options:
                name: 'wallabag.import.shaarli'
                type: topic
        import_pocket_html:
            connection: default
            exchange_options:
                name: 'wallabag.import.pocket_html'
                type: topic
    consumers:
        import_pocket:
            connection: default
            exchange_options:
                name: 'wallabag.import.pocket'
                type: topic
            queue_options:
                name: 'wallabag.import.pocket'
            callback: wallabag.consumer.amqp.pocket
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_readability:
            connection: default
            exchange_options:
                name: 'wallabag.import.readability'
                type: topic
            queue_options:
                name: 'wallabag.import.readability'
            callback: wallabag.consumer.amqp.readability
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_instapaper:
            connection: default
            exchange_options:
                name: 'wallabag.import.instapaper'
                type: topic
            queue_options:
                name: 'wallabag.import.instapaper'
            callback: wallabag.consumer.amqp.instapaper
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_pinboard:
            connection: default
            exchange_options:
                name: 'wallabag.import.pinboard'
                type: topic
            queue_options:
                name: 'wallabag.import.pinboard'
            callback: wallabag.consumer.amqp.pinboard
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_delicious:
            connection: default
            exchange_options:
                name: 'wallabag.import.delicious'
                type: topic
            queue_options:
                name: 'wallabag.import.delicious'
            callback: wallabag.consumer.amqp.delicious
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_wallabag_v1:
            connection: default
            exchange_options:
                name: 'wallabag.import.wallabag_v1'
                type: topic
            queue_options:
                name: 'wallabag.import.wallabag_v1'
            callback: wallabag.consumer.amqp.wallabag_v1
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_wallabag_v2:
            connection: default
            exchange_options:
                name: 'wallabag.import.wallabag_v2'
                type: topic
            queue_options:
                name: 'wallabag.import.wallabag_v2'
            callback: wallabag.consumer.amqp.wallabag_v2
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_elcurator:
            connection: default
            exchange_options:
                name: 'wallabag.import.elcurator'
                type: topic
            queue_options:
                name: 'wallabag.import.elcurator'
            callback: wallabag.consumer.amqp.elcurator
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_omnivore:
            connection: default
            exchange_options:
                name: 'wallabag.import.omnivore'
                type: topic
            queue_options:
                name: 'wallabag.import.omnivore'
            callback: wallabag.consumer.amqp.omnivore
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_firefox:
            connection: default
            exchange_options:
                name: 'wallabag.import.firefox'
                type: topic
            queue_options:
                name: 'wallabag.import.firefox'
            callback: wallabag.consumer.amqp.firefox
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_chrome:
            connection: default
            exchange_options:
                name: 'wallabag.import.chrome'
                type: topic
            queue_options:
                name: 'wallabag.import.chrome'
            callback: wallabag.consumer.amqp.chrome
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_shaarli:
            connection: default
            exchange_options:
                name: 'wallabag.import.shaarli'
                type: topic
            queue_options:
                name: 'wallabag.import.shaarli'
            callback: wallabag.consumer.amqp.shaarli
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}
        import_pocket_html:
            connection: default
            exchange_options:
                name: 'wallabag.import.pocket_html'
                type: topic
            queue_options:
                name: 'wallabag.import.pocket_html'
            callback: wallabag.consumer.amqp.pocket_html
            qos_options: {prefetch_count: "%rabbitmq_prefetch_count%"}

fos_js_routing:
    routes_to_expose:
        - homepage
        - starred
        - archive
        - all
        - tag
        - config
        - import
        - developer
        - howto
        - fos_user_security_logout
        - new

jms_serializer:
    handlers:
        # to be removed if we switch to (default) ISO8601 datetime instead of ATOM
        # see: https://github.com/schmittjoh/JMSSerializerBundle/pull/494
        datetime:
            default_format: "Y-m-d\\TH:i:sO" # ATOM

# see https://github.com/symfony/symfony-standard/pull/1133
sensio_framework_extra:
   router:
        annotations: false

httplug:
    clients:
        wallabag:
            factory: Wallabag\Helper\HttpClientFactory
            config:
                defaults:
                    timeout: 10
            plugins: ['httplug.plugin.logger']
    discovery:
        client: false

# define custom entity so we can override length attribute to fix utf8mb4 issue
craue_config:
    entity_name: Wallabag\Entity\InternalSetting

when@dev:
    maker:
        root_namespace: 'Wallabag'
