imports:
    - { resource: parameters.yml }
    - { resource: security.yaml }
    - { resource: ../../config/services.yaml }
    - { resource: ../../config/packages/craue_config.yaml }
    - { resource: ../../config/packages/dama_doctrine_test_bundle.yaml }
    - { resource: ../../config/packages/doctrine.yaml }
    - { resource: ../../config/packages/doctrine_migrations.yaml }
    - { resource: ../../config/packages/fos_js_routing.yaml }
    - { resource: ../../config/packages/fos_oauth_server.yaml }
    - { resource: ../../config/packages/fos_rest.yaml }
    - { resource: ../../config/packages/fos_user.yaml }
    - { resource: ../../config/packages/framework.yaml }
    - { resource: ../../config/packages/httplug.yaml }
    - { resource: ../../config/packages/jms_serializer.yaml }
    - { resource: ../../config/packages/kphoen_rulerz.yaml }
    - { resource: ../../config/packages/mailer.yaml }
    - { resource: ../../config/packages/maker.yaml }
    - { resource: ../../config/packages/monolog.yaml }
    - { resource: ../../config/packages/nelmio_api_doc.yaml }
    - { resource: ../../config/packages/nelmio_cors.yaml }
    - { resource: ../../config/packages/old_sound_rabbit_mq.yaml }
    - { resource: ../../config/packages/routing.yaml }
    - { resource: ../../config/packages/scheb_two_factor.yaml }
    - { resource: ../../config/packages/sensio_framework_extra.yaml }
    - { resource: ../../config/packages/sentry.yaml }
    - { resource: ../../config/packages/stof_doctrine_extensions.yaml }
    - { resource: ../../config/packages/translation.yaml }
    - { resource: ../../config/packages/twig.yaml }
    - { resource: ../../config/packages/validator.yaml }
    - { resource: ../../config/packages/wallabag.yaml }
    - { resource: ../../config/packages/web_profiler.yaml }

parameters:
    # Allows to use the live reload feature for changes in assets
    use_webpack_dev_server: false
    craue_config.cache_adapter.class: Craue\ConfigBundle\CacheAdapter\SymfonyCacheComponentAdapter
    env(DATABASE_URL): '%database_scheme%://%database_user%:%database_password%@%database_host%:%database_port%/%database_name%?unix_socket=%database_socket%&charset=%database_charset%'
