imports:
    - { resource: config_dev.yaml }
    - { resource: parameters_test.yaml }
    - { resource: services_test.yaml }

parameters:
    fosuser_registration: true
    wallabag_dbname_suffix: '_test'

dama_doctrine_test:
    enable_static_connection: true
    enable_static_meta_data_cache: true
    enable_static_query_cache: true
