imports:
    - { resource: config.yaml }

framework:
    profiler:
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        console:
            type: console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ['!event', '!doctrine']
        console_very_verbose:
            type: console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: [doctrine]

# If you want to use cache for queries used in WallabagExtension
# Uncomment the following lines
#doctrine:
#    orm:
#        metadata_cache_driver: apcu
#        result_cache_driver: apcu
#        query_cache_driver: apcu
