app:
    resource: ../../src/Controller/
    type: annotation

doc-api:
    resource: "@NelmioApiDocBundle/config/routing/swaggerui.xml"
    prefix: /api/doc

doc-api-json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

homepage:
    path: "/{page}"
    defaults:
        _controller: 'Wallabag\Controller\EntryController::showUnreadAction'
        page : 1
    requirements:
        page: \d+

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

craue_config_settings_modify:
    path: /settings
    defaults:
        _controller: 'Craue\ConfigBundle\Controller\SettingsController::modifyAction'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check

# redirect RSS feed to Atom
rss_to_atom_unread:
    path: /{username}/{token}/unread.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: unread_feed
        permanent: true

rss_to_atom_archive:
    path: /{username}/{token}/archive.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: archive_feed
        permanent: true

rss_to_atom_starred:
    path: /{username}/{token}/starred.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: starred_feed
        permanent: true

rss_to_atom_all:
    path: /{username}/{token}/all.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: all_feed
        permanent: true

rss_to_atom_tags:
    path: /{username}/{token}/tags/{slug}.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: tag_feed
        permanent: true
