parameters:
    database_driver: ${DATABASE_DRIVER:-pdo_sqlite}
    database_host: ${DATABASE_HOST:-127.0.0.1}
    database_port: ${DATABASE_PORT:-~}
    database_name: ${DATABASE_NAME:-symfony}
    database_user: ${DATABASE_USER:-root}
    database_password: ${DATABASE_PASSWORD:-~}
    database_path: '${DATABASE_PATH:-"%kernel.project_dir%/data/db/wallabag.sqlite"}'
    database_table_prefix: ${DATABASE_TABLE_PREFIX:-wallabag_}
    database_socket: null
    database_charset: ${DATABASE_CHARSET:-utf8}

    domain_name: ${DOMAIN_NAME:-https://www.example.com}
    server_name: ${SERVER_NAME:-"Your wallabag instance"}

    mailer_dsn: ${MAILER_DSN:-"smtp://127.0.0.1"}

    locale: ${LOCALE:-en}

    # A secret key that's used to generate certain security-related tokens
    secret: ${SECRET:-~}

    # two factor stuff
    twofactor_sender: ${TWOFACTOR_SENDER:-no-reply@wallabag.org}

    # fosuser stuff
    fosuser_registration: ${FOSUSER_REGISTRATION:-false}
    fosuser_confirmation: ${FOSUSER_CONFIRMATION:-true}

    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: ${FROM_EMAIL:-wallabag@example.com}

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: ${RABBITMQ_HOST:-rabbitmq}
    rabbitmq_port: ${RABBITMQ_PORT:-5672}
    rabbitmq_user: ${RABBITMQ_USER:-guest}
    rabbitmq_password: ${RABBITMQ_PASSWORD:-guest}
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: ${REDIS_SCHEME:-tcp}
    redis_host: ${REDIS_HOST:-redis}
    redis_port: ${REDIS_PORT:-6379}
    redis_path: ${REDIS_PATH:-~}
    redis_password: ${REDIS_PASSWORD:-~}

    # Sentry
    sentry_dsn: ${SENTRY_DSN:-~}
