app:
    resource: ../src/Controller/
    type: annotation

doc-api-json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

homepage:
    path: "/{page}"
    defaults:
        _controller: 'Wallabag\Controller\EntryController::showUnreadAction'
        page : 1
    requirements:
        page: \d+

# redirect RSS feed to Atom
rss_to_atom_unread:
    path: /{username}/{token}/unread.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: unread_feed
        permanent: true

rss_to_atom_archive:
    path: /{username}/{token}/archive.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: archive_feed
        permanent: true

rss_to_atom_starred:
    path: /{username}/{token}/starred.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: starred_feed
        permanent: true

rss_to_atom_all:
    path: /{username}/{token}/all.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: all_feed
        permanent: true

rss_to_atom_tags:
    path: /{username}/{token}/tags/{slug}.xml
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction'
        route: tag_feed
        permanent: true
