<?php

namespace WallabagBundle\Repository;

use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;

/**
 * EntriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntriesRepository extends EntityRepository
{
  /*  public function findUnreadByUser($userId)
    {
        return $this->createQueryBuilder('e')
            ->where('e.is_read = 0')
            ->andWhere('e.user_id = :userId')
            ->setParameter('userId', $userId)
            ->getQuery();
    }*/
    public function findUnreadByUser($userId)
    {
        $qb = $this->createQueryBuilder('e')
            ->select('e')
            ->where('e.isRead = 0')
            ->andWhere('e.userId =:userId')->setParameter('userId', $userId)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        return $qb;
    }
}
