name: "Upload release package"

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

      - name: "Install PHP"
        uses: "shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240" # 2.37.2
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: pecl, composer:2.2
          extensions: pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, curl, imagick, pgsql, gd, tidy
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Node"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Create the package
        run: make release VERSION=${{ github.event.release.tag_name }}

      - name: Upload the package to the release
        uses: shogo82148/actions-upload-release-asset@d0cb37bb764791e72e64e643cd7056f74f1e77d7 # v1.10.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/wllbg-release/wallabag-${{ github.event.release.tag_name }}.tar.gz
